# Generated by Django 4.0.5 on 2022-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_postteacher_tiputilizator_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiputilizator',
            name='TipUtiliz',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=255, null=True),
        ),
    ]
