# Generated by Django 4.0.5 on 2022-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_tiputilizator_tiputiliz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiputilizator',
            name='Password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiputilizator',
            name='FirstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tiputilizator',
            name='LastName',
            field=models.CharField(max_length=255),
        ),
    ]
