# Generated by Django 4.0.5 on 2022-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_tiputilizator_password_alter_tiputilizator_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiputilizator',
            name='TipUtiliz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
