# Generated by Django 4.0.5 on 2022-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_alter_tiputilizator_tiputiliz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='TipUtiliz',
            new_name='tiputilizator',
        ),
        migrations.RenameField(
            model_name='tiputilizator',
            old_name='Name',
            new_name='username',
        ),
    ]
