# Generated by Django 4.0.5 on 2022-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_rename_email_tiputilizator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiputilizator',
            name='iduser',
            field=models.IntegerField(null=True),
        ),
    ]
