# Generated by Django 4.0.5 on 2022-07-01 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0011_remove_tiputilizator_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiputilizator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tiputilizator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tiputilizator',
            name='username',
        ),
        migrations.AddField(
            model_name='tiputilizator',
            name='imag',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tiputilizator',
            name='preference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tiputilizator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
