# Generated by Django 4.0.5 on 2022-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_remove_tiputilizator_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiputilizator',
            name='imag',
        ),
        migrations.RemoveField(
            model_name='tiputilizator',
            name='password',
        ),
        migrations.AddField(
            model_name='tiputilizator',
            name='biograpghy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
