# Generated by Django 4.0.5 on 2022-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_remove_tiputilizator_imag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiputilizator',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
