# Generated by Django 4.0.5 on 2022-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_quiz_question_marks_of_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks_of_user',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='marks_of_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Marks_Of_User',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
