# Generated by Django 4.0.5 on 2022-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0020_quesmodel_remove_marks_of_user_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tiputilizator',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
