# Generated by Django 4.0.5 on 2022-07-10 14:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_remove_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prof_user', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('imag', models.ImageField(null=True, upload_to='images')),
                ('creation_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostLessonTeacher',
        ),
    ]
