# Generated by Django 4.0.5 on 2022-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0024_alter_courses_file_alter_courses_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='imag',
            field=models.ImageField(null=True, upload_to='imag'),
        ),
    ]
