# Generated by Django 4.0.5 on 2022-07-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0026_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
