# Generated by Django 4.0.5 on 2022-07-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_delete_message_remove_profile_user_delete_quesmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
