# Generated by Django 4.0.5 on 2022-07-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_delete_message_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='file',
        ),
    ]
