# Generated by Django 4.0.5 on 2022-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_remove_courses_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='utype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
