# Generated by Django 4.0.5 on 2022-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_teacher_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.ImageField(null=True, upload_to='video'),
        ),
    ]
