# Generated by Django 4.0.5 on 2022-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_alter_courses_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='document',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video',
            field=models.ImageField(null=True, upload_to='video'),
        ),
    ]
